# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CharSer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CharSer
  #pod 'RealmSwift', '~> 5.4.8'
  
  target 'CharSerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CharSerUITests' do
    # Pods for testing
  end

end
